"""add_products_and_orders

Revision ID: 5786444b71d6
Revises: 001_initial
Create Date: 2026-06-18 05:21:13.417981+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5786444b71d6'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_product_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('minimum_price', sa.Float(), nullable=False),
    sa.Column('target_margin', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('popularity_index', sa.Float(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_external_product_id'), 'products', ['external_product_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.add_column('customers', sa.Column('external_customer_id', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('customer_segment', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('total_spend', sa.Float(), nullable=False))
    op.add_column('customers', sa.Column('average_order_value', sa.Float(), nullable=False))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('last_purchase_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_column('customers', 'last_purchase_date')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'average_order_value')
    op.drop_column('customers', 'total_spend')
    op.drop_column('customers', 'customer_segment')
    op.drop_column('customers', 'external_customer_id')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_external_product_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
